import { resolve, join, basename } from 'path';
import { mkdir, writeFile, access } from 'fs/promises';
import { homedir } from 'os';
import { randomUUID } from 'crypto';
import { spawn } from 'child_process';

function git(cwd: string, args: string[]): Promise<{ code: number; stderr: string }> {
  return new Promise(resolve => {
    const proc = spawn('git', args, { cwd, stdio: ['ignore', 'pipe', 'pipe'] });
    let stderr = '';
    proc.stderr?.on('data', c => { stderr += String(c); });
    proc.on('exit', code => resolve({ code: code ?? 0, stderr }));
    proc.on('error', () => resolve({ code: 127, stderr: 'spawn error' }));
  });
}

function configTemplate(transportPath: string): string {
  return [
    '# Crosstalk runtime config — generated by crosstalk init',
    '# Edit the agents list, then run: crosstalk --config <this file>',
    '',
    `transport: ${transportPath}`,
    '',
    'agents:',
    '  - name: concierge',
    '    cli: claude --print',
    '',
  ].join('\n');
}

export async function runInit(argv: string[]): Promise<void> {
  const transportIdx = argv.indexOf('--transport');
  const transportPath = resolve(transportIdx !== -1 ? argv[transportIdx + 1] : process.cwd());

  console.log(`crosstalk init\ntransport: ${transportPath}\n`);

  // Verify this is a Crosstalk transport
  try {
    await access(join(transportPath, 'manifest', 'custom', 'CROSSTALK.md'));
    console.log('  transport verified');
  } catch {
    console.error(`error: manifest/custom/CROSSTALK.md not found at ${transportPath}`);
    console.error('  Run this inside a cloned Crosstalk transport, or pass --transport <path>.');
    process.exit(1);
  }

  // Create a channel
  const channelGuid = randomUUID();
  const channelRelPath = join('data', 'channels', channelGuid);
  const channelDir = join(transportPath, channelRelPath);
  await mkdir(channelDir, { recursive: true });
  await writeFile(join(channelDir, '.gitkeep'), '', 'utf-8');
  console.log(`  channel created: ${channelRelPath}`);

  // Commit it to the transport
  await git(transportPath, ['add', channelRelPath]);
  const { code: commitCode } = await git(transportPath, [
    'commit', '-m', 'init: create first channel',
  ]);
  if (commitCode === 0) {
    console.log('  channel committed');
  }

  // Push — non-fatal if it fails
  const { code: pushCode, stderr } = await git(transportPath, ['push', 'origin', 'main']);
  if (pushCode === 0) {
    console.log('  pushed to origin');
  } else {
    console.warn('  push failed — run "git push" manually when ready');
    if (stderr.trim()) console.warn(`  ${stderr.trim()}`);
  }

  // Write config to ~/.config/crosstalk/<repo-name>/config.yaml
  const repoName = basename(transportPath);
  const configDir = join(homedir(), '.config', 'crosstalk', repoName);
  const configPath = join(configDir, 'config.yaml');
  await mkdir(configDir, { recursive: true });
  await writeFile(configPath, configTemplate(transportPath), 'utf-8');
  console.log(`  config written: ${configPath}`);

  console.log(`
Next steps:
  1. Edit ${configPath} to set your agents
  2. Run: crosstalk --config ${configPath}
`);
}
