import { resolve, join, basename } from 'path';
import { mkdir, writeFile, access } from 'fs/promises';
import { homedir, hostname as osHostname, userInfo } from 'os';
import { randomUUID } from 'crypto';
import { spawn } from 'child_process';
import * as readline from 'readline';

function git(cwd: string, args: string[]): Promise<{ code: number; stderr: string }> {
  return new Promise(resolve => {
    const proc = spawn('git', args, { cwd, stdio: ['ignore', 'pipe', 'pipe'] });
    let stderr = '';
    proc.stderr?.on('data', c => { stderr += String(c); });
    proc.on('exit', code => resolve({ code: code ?? 0, stderr }));
    proc.on('error', () => resolve({ code: 127, stderr: 'spawn error' }));
  });
}

function prompt(rl: readline.Interface, question: string): Promise<string> {
  return new Promise(resolve => rl.question(question, resolve));
}

function hostFileTemplate(alias: string, hostname: string, username: string, actorName: string, cli: string): string {
  return [
    '---',
    `alias: ${alias}`,
    `hostname: ${hostname}`,
    `username: ${username}`,
    'actors:',
    `  ${actorName}:`,
    `    default: ${cli}`,
    '---',
    '',
  ].join('\n');
}

function thinConfigTemplate(transportPath: string, alias: string): string {
  return [
    '# Crosstalk runtime config — generated by crosstalk init',
    `transport: ${transportPath}`,
    `host: ${alias}`,
    '',
  ].join('\n');
}

export async function runInit(argv: string[]): Promise<void> {
  const transportIdx = argv.indexOf('--transport');
  const transportPath = resolve(transportIdx !== -1 ? argv[transportIdx + 1] : process.cwd());

  console.log(`crosstalk init\ntransport: ${transportPath}\n`);

  // Verify this is a Crosstalk transport
  try {
    await access(join(transportPath, 'manifest', 'custom', 'CROSSTALK.md'));
    console.log('  transport verified');
  } catch {
    console.error(`error: manifest/custom/CROSSTALK.md not found at ${transportPath}`);
    console.error('  Run this inside a cloned Crosstalk transport, or pass --transport <path>.');
    process.exit(1);
  }

  const detectedHostname = osHostname();
  const detectedUsername = (() => { try { return userInfo().username; } catch { return ''; } })();
  const defaultAlias     = detectedUsername || detectedHostname;
  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  console.log('');
  const alias     = (await prompt(rl, `  host alias     [${defaultAlias}]: `)).trim() || defaultAlias;
  const actorName = (await prompt(rl, `  actor name     [concierge]: `)).trim() || 'concierge';
  const cli       = (await prompt(rl, `  CLI command    [claude --print]: `)).trim() || 'claude --print';
  rl.close();
  console.log('');

  // Create manifest/hosts/ and write host file
  const hostsDir    = join(transportPath, 'manifest', 'hosts');
  const hostRelPath = join('manifest', 'hosts', `${alias}.md`);
  await mkdir(hostsDir, { recursive: true });
  await writeFile(join(transportPath, hostRelPath), hostFileTemplate(alias, detectedHostname, detectedUsername, actorName, cli), 'utf-8');
  console.log(`  host file created: ${hostRelPath}`);

  // Create a channel
  const channelGuid    = randomUUID();
  const channelRelPath = join('data', 'channels', channelGuid);
  await mkdir(join(transportPath, channelRelPath), { recursive: true });
  await writeFile(join(transportPath, channelRelPath, '.gitkeep'), '', 'utf-8');
  console.log(`  channel created:   ${channelRelPath}`);

  // Commit both to the transport
  await git(transportPath, ['add', hostRelPath, channelRelPath]);
  const { code: commitCode } = await git(transportPath, [
    'commit', '-m', `init: add host file and channel for ${alias}`,
  ]);
  if (commitCode === 0) console.log('  committed to transport');

  // Push — non-fatal if it fails
  const { code: pushCode, stderr } = await git(transportPath, ['push', 'origin', 'main']);
  if (pushCode === 0) {
    console.log('  pushed to origin');
  } else {
    console.warn('  push failed — run "git push" manually when ready');
    if (stderr.trim()) console.warn(`  ${stderr.trim()}`);
  }

  // Write thin config to ~/.crosstalk/<repo-name>/config.yaml
  const repoName   = basename(transportPath);
  const configDir  = join(homedir(), '.crosstalk', repoName);
  const configPath = join(configDir, 'config.yaml');
  await mkdir(configDir, { recursive: true });
  await writeFile(configPath, thinConfigTemplate(transportPath, alias), 'utf-8');
  console.log(`  config written:    ${configPath}`);

  console.log(`
Next steps:
  1. Add more actors or tiers to ${hostRelPath}
  2. Run: crosstalk --config ${configPath}
`);
}
